# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EnvPull < Formula
  desc "Universal Secrets Adapter"
  homepage "https://github.com/dynamicHarsh/env-pull"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dynamicHarsh/env-pull/releases/download/v0.1.1/env-pull_0.1.1_darwin_amd64.tar.gz"
      sha256 "855e000135fb4282409500a63befbe624d657f92b07f8d3eb4c4aab02f8895ce"

      define_method(:install) do
        bin.install "env-pull"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dynamicHarsh/env-pull/releases/download/v0.1.1/env-pull_0.1.1_darwin_arm64.tar.gz"
      sha256 "99c8b0b20cbf02236f63e55e2530d5a18955effc0b0acad6c1e834ce5adb3743"

      define_method(:install) do
        bin.install "env-pull"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dynamicHarsh/env-pull/releases/download/v0.1.1/env-pull_0.1.1_linux_amd64.tar.gz"
      sha256 "e64e3e8fadc8764d314b592109f6ddf66f22826c87293eadf6919aa44ef69e79"
      define_method(:install) do
        bin.install "env-pull"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dynamicHarsh/env-pull/releases/download/v0.1.1/env-pull_0.1.1_linux_arm64.tar.gz"
      sha256 "e6d823ceb43fb7a573a1da87e24b02e25355a7d0b585cc2a7e574fc8575ea681"
      define_method(:install) do
        bin.install "env-pull"
      end
    end
  end

  test do
    system "#{bin}/env-pull", "--version"
  end
end
