# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EnvPull < Formula
  desc "Universal Secrets Adapter"
  homepage "https://github.com/dynamicHarsh/env-pull"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dynamicHarsh/env-pull/releases/download/v0.1.2/env-pull_0.1.2_darwin_amd64.tar.gz"
      sha256 "034ebeeec7878c20510a8181eaf0da566fd5d4915898fd524383a5124c2ce068"

      define_method(:install) do
        bin.install "env-pull"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dynamicHarsh/env-pull/releases/download/v0.1.2/env-pull_0.1.2_darwin_arm64.tar.gz"
      sha256 "3e1022ef9cc311c3680ec8f6ee5100f3adf6738df3584ecf52d03b89b49595d5"

      define_method(:install) do
        bin.install "env-pull"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dynamicHarsh/env-pull/releases/download/v0.1.2/env-pull_0.1.2_linux_amd64.tar.gz"
      sha256 "ad4cd70302ace9022d7cb85faec70c0d848eb5e105a14caed3e9e6f95f24e097"
      define_method(:install) do
        bin.install "env-pull"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dynamicHarsh/env-pull/releases/download/v0.1.2/env-pull_0.1.2_linux_arm64.tar.gz"
      sha256 "78a1b378d8b8ef23f98f20e54baf83f60d652caa906a2da36dad1bb6bad2f694"
      define_method(:install) do
        bin.install "env-pull"
      end
    end
  end

  test do
    system "#{bin}/env-pull", "--version"
  end
end
