# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Inject < Formula
  desc "Universal Secrets Adapter"
  homepage "https://github.com/dynamicHarsh/env-pull"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dynamicHarsh/env-pull/releases/download/v0.1.3/inject_0.1.3_darwin_amd64.tar.gz"
      sha256 "784857722ab79b7fbbaa8c442a27aeb9286e292da964648eb6e27522b87b180f"

      define_method(:install) do
        bin.install "inject"
        bin.install_symlink "inject" => "env-pull"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dynamicHarsh/env-pull/releases/download/v0.1.3/inject_0.1.3_darwin_arm64.tar.gz"
      sha256 "4d3305bc00c8b7ed790ae71b696209756a918ce535d4d60001e0d1e65e5425cc"

      define_method(:install) do
        bin.install "inject"
        bin.install_symlink "inject" => "env-pull"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dynamicHarsh/env-pull/releases/download/v0.1.3/inject_0.1.3_linux_amd64.tar.gz"
      sha256 "22b1a4d23e3b9f68f0b847abe82149eba150bcdd65bf6f42435600dcfa72cc3d"
      define_method(:install) do
        bin.install "inject"
        bin.install_symlink "inject" => "env-pull"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dynamicHarsh/env-pull/releases/download/v0.1.3/inject_0.1.3_linux_arm64.tar.gz"
      sha256 "5ec7335d0c527a51ffa28cd4553f892579a1902a972c1890476d234c6e0e22a6"
      define_method(:install) do
        bin.install "inject"
        bin.install_symlink "inject" => "env-pull"
      end
    end
  end

  test do
    system "#{bin}/inject", "--help"
  end
end
