# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Inject < Formula
  desc "Universal Secrets Adapter"
  homepage "https://github.com/dynamicHarsh/env-pull"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dynamicHarsh/env-pull/releases/download/v0.2.0/inject_0.2.0_darwin_amd64.tar.gz"
      sha256 "d27d46960656a6dfdfe1619c25001d093dd9a4175794f32b1ed257718534e03a"

      define_method(:install) do
        bin.install "inject"
        bin.install_symlink "inject" => "env-pull"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dynamicHarsh/env-pull/releases/download/v0.2.0/inject_0.2.0_darwin_arm64.tar.gz"
      sha256 "053547259cbe523ba4484449c888b065c5a7012b6c941d6d48d2df939da2e83d"

      define_method(:install) do
        bin.install "inject"
        bin.install_symlink "inject" => "env-pull"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dynamicHarsh/env-pull/releases/download/v0.2.0/inject_0.2.0_linux_amd64.tar.gz"
      sha256 "fc2da76fb012962919f6f94e277b947bd0fa35d5c372e4a766b5850c9fee7386"
      define_method(:install) do
        bin.install "inject"
        bin.install_symlink "inject" => "env-pull"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dynamicHarsh/env-pull/releases/download/v0.2.0/inject_0.2.0_linux_arm64.tar.gz"
      sha256 "6810d188a45c111d34f185b1c47c85f09c57bac5abc9714274079460b7039f6e"
      define_method(:install) do
        bin.install "inject"
        bin.install_symlink "inject" => "env-pull"
      end
    end
  end

  test do
    system "#{bin}/inject", "--help"
  end
end
