# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Inject < Formula
  desc "Universal Secrets Adapter"
  homepage "https://github.com/dynamicHarsh/env-pull"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dynamicHarsh/inject/releases/download/v0.2.1/inject_0.2.1_darwin_amd64.tar.gz"
      sha256 "6908d3abf3a3aefc40d72658b13cb61a6659fae155f618263a5300d55cdc6891"

      define_method(:install) do
        bin.install "inject"
        bin.install_symlink "inject" => "env-pull"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dynamicHarsh/inject/releases/download/v0.2.1/inject_0.2.1_darwin_arm64.tar.gz"
      sha256 "ba7c6883db5a13a10ce6dd520e605aea82190702f96d5d2e87bbd5ee73be22da"

      define_method(:install) do
        bin.install "inject"
        bin.install_symlink "inject" => "env-pull"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dynamicHarsh/inject/releases/download/v0.2.1/inject_0.2.1_linux_amd64.tar.gz"
      sha256 "c85f324d4a80e090d0c3066cad355af5362d089d533cf807941c037214df325a"
      define_method(:install) do
        bin.install "inject"
        bin.install_symlink "inject" => "env-pull"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dynamicHarsh/inject/releases/download/v0.2.1/inject_0.2.1_linux_arm64.tar.gz"
      sha256 "e79613c6ebafbc8e15a06a9e3f8a8fc137d327051562849e9a87c15ac08c0f27"
      define_method(:install) do
        bin.install "inject"
        bin.install_symlink "inject" => "env-pull"
      end
    end
  end

  test do
    system "#{bin}/inject", "--help"
  end
end
